# Generated by Django 4.2.3 on 2023-08-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_user_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
