# Generated by Django 4.2.3 on 2023-08-12 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['target_type', 'target_id'], name='news_action_target__15a47a_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['-created'], name='news_action_created_2e2248_idx'),
        ),
    ]
