# Generated by Django 4.2.3 on 2023-08-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
